/**********************************************************************************************************************
 * \file Cpu0_Main.c        TODO: remove license comment if not strictly required
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Blinky LED
 * \abstract An LED is blinking based on the timing given by a wait function.
 * \description A wait function is used to add delays between switching on and switching off an LED on port pin P10.2.
 * \name Blinky_LED_1_KIT_TC375_SB
 * \version V1.0.0
 * \board hitex ShieldBuddy, KIT_A2G_TC375_ARD_SB, TC37xTP_A-Step
 * \keywords LED, blinky, GPIO, General Port Input Output, AURIX, Blinky_LED_1
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_Blinky_LED_1_KIT_TC375_SB-TR-v01_00_00-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC37A_iLLD_UM_1_0_1_12_1.chm
 * \lastUpdated 2020-12-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "common/usb_data_types.h"
#include "common/spi_data_types.h"
#include "common/command_queue.h"
#include "command_queue.h"
#include "cmd/general_cmd.h"
#include "cmd/seq_cmd.h"
#include "cmd/bypass_cmd.h"
#include "cmd/cont_read_cmd.h"
#include "cmd/gpio_cmd.h"
#include "cmd/watchdog.h"
#include "periphery/led.h"
#include "periphery/usb.h"
#include "periphery/timer.h"
#include "periphery/control_pins.h"
#include "periphery/gpio.h"
#include "top/status.h"
#include "top/spi_wrapper.h"
#include "top/usb_wrapper.h"
#include "led.h"
#include "Bsp.h"

// for debug messages on button press JS 4/2024
#include "button.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define WAIT_TIME 2   /*mseconds */




/** \brief Main function
 */
void core0_main(void)
{
    /* add some globals for debugging*/
    //static uint16 debug_counter;
    //uint8 debug_ret;
    //uint32 buffer_new;


    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialize the LED port pins      */
    InitLEDs();


    /* Init pins*/
    ConfigureSelectPin();
    InitGPIOPins();

    // Init USB
    USBInit();

    /* Initialize the QSPI modules and the LED */
    QSPIInit();

    // Init message pump
    QueueInit();

    // Init status
    InitStatus();

    // Init timer module
    InitGpt12Timer();

    // Start service irq
    // JS: 19.4.2024 inhibit timers for not interrupt debugging
    //StartServiceTimer();

    // Start general timer
    //JS: 19.4.2024 inhibit for better debugging
    //StartGeneralTimer();

    // Local temporary variable for receiving data
    USBReceiveData receivedPackage;

    // Local variable to store dispatched command
    USBReceiveData cmdPackage;

    // Flag for USB receive status
    boolean isSuccessfulFlag = FALSE;
    while(1)
    {

        //ToggleLED1();
        Blink_LED1_1Hz();

       if(GetButtonState())
       {
           OnLED2();

//           buffer_new = 0xF8000007;// shall produce same as 000000
//
//           debug_ret =  CRC3MI(buffer_new);
//
//           QSPIWriteFast(WD_CONFIG0_ADDRESS , debug_ret);
//
//           buffer_new = 0x00000000; // shall produce 7
//
//           debug_ret =  CRC3MI(buffer_new);
//
//           buffer_new = 0x00AABB00; // shall produce 5
//
//           debug_ret =  CRC3MI(buffer_new);

//            QSPIWriteFast(WD_CONFIG0_ADDRESS , debug_counter);
//
//               /*Initialize temporary variables*/
//               uint8 buffer[10];
//               Ifx_SizeT itemCounter = 0;
//
//               // Fill buffer with package
//               buffer[itemCounter] = 0x40;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = 0x41;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = 0x31;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = 0x35;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = 0x20;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = (uint8)debug_counter;             /* Start package byte  */
//               itemCounter++;
//               buffer[itemCounter] = 0x20;             /* Start package byte  */
//               itemCounter++;
//
//           SendUSBData(buffer, &itemCounter);
//           debug_counter++;
       }
       else
       {
           OffLED2();
       }

        // wait for 2ms for next polling
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME));

        // Receive package (assumes it already in in buffer of UART
        isSuccessfulFlag = ReceiveUSBPackage(&receivedPackage);

        // Proceed with execution if message received or queue is not empty
        if (isSuccessfulFlag == TRUE)
        {
            // Store data to queue and proceed
            QueueWrite(&receivedPackage);
            /* package sucessul received*/
            ToggleLED3();
            // Clean package
            receivedPackage.command = _USB_CMD_MIN;
        }
        else if (QueueGetOccupiedSize() == 0)
        {
            // Queue is not empty - proceed
            continue;
        }

        // Dispatch command
        // Also correctly handles empty queue dispatch

        cmdPackage = QueueRead(); //TODO: include not found

        // Command handling. Empty queue will be handled in max command case
        switch (cmdPackage.command)
        {
            case USB_CMD_IS_ALIVE:
                CmdIsAlive(&cmdPackage);
                break;
            case USB_CMD_SPI_INSTRUCTION:
                //CmdSpiInstuction(&cmdPackage);
                handleCmdInstr(&cmdPackage);
                break;
            case USB_CMD_READ_DEV_ID:
                getAsicDeviceId(&cmdPackage);
                break;
            // case :
            //     break;
            // case :
            //     break;
            // case :
            //     break;
            // case :
            //     break;
            case USB_CMD_GET_MCU_VERSION:
                CmdGetMcuVersion(&cmdPackage);
                break;
            case USB_CMD_GET_MCU_BUILD_DATE:
                CmdGetMcuBuildDate(&cmdPackage);
                break;
            case USB_CMD_GET_MCU_BUILD_TIME:
                CmdGetMcuBuildTime(&cmdPackage);
                break;


            case _USB_CMD_MAX:
                break;
            default :
                break;
        }
    }
}
