/**********************************************************************************************************************
 * \file cont_read.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef CONT_READ_CMD_H_
#define CONT_READ_CMD_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "common/usb_data_types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Handling USB_CMD_CONFIGURE_READING command from PC
 * Populates read sequence for continuous read feature. Allows enable of continuous read
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdConfigureReading(USBReceiveData const * const commandPackage);

/** \brief Handling USB_CMD_START_READING command from PC
 * Starts continuous reading if it was configured. Enables continuous read interrupts
 * Msg_id of this command will be used in responses of read iterations
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdStartReading(USBReceiveData const * const commandPackage);

/** \brief Handling USB_CMD_STOP_READING command from PC
 * Stops continuous reading. Disables continuous read interrupts
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdStopReading(USBReceiveData const * const commandPackage);

/** \brief Handling INT_CMD_CONT_READ command
 * Performs continuous read iteration (single read of set of registers) if it was configured
 * Msg_id of response is set by start reading.
 *
 * \return Nothing
 */
void IntCmdContRead(void);

#endif /* CONT_READ_CMD_H_ */
