/**********************************************************************************************************************
 * \file general_cmd.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "common/usb_data_types.h"
#include "common/spi_data_types.h"
#include "common/command_queue.h"
#include "common/bit_manipulation.h"
#include "top/spi_wrapper.h"
#include "top/usb_wrapper.h"
#include "top/version.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void CmdIsAlive(USBReceiveData const * const commandPackage)
{
    USBTransmitData packageToSend;

    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);
    packageToSend.status = USB_STATUS_ACK;
    packageToSend.dataLength = 0;








    // Send data back to MCU
    SendUSBPackage(&packageToSend);
}



void CmdGetMcuVersion(USBReceiveData const * const commandPackage)
{
    USBTransmitData packageToSend;

    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);
    packageToSend.status = USB_STATUS_ACK;
    packageToSend.dataLength = 8;
    packageToSend.data[0] = 0; // shall return VERSION_MAJOR;
    packageToSend.data[1] = 1 ; // shall rezturn VERSION_MINOR;
    packageToSend.data[2] = 2 ; // VERSION_PATCH;
    packageToSend.data[3] = '.';
    packageToSend.data[4] = BUILD_MONTH_CH0;
    packageToSend.data[5] = BUILD_MONTH_CH1;
    packageToSend.data[6] = BUILD_DAY_CH0;
    packageToSend.data[7] = BUILD_DAY_CH1;


    // Send data back to MCU
    SendUSBPackage(&packageToSend);
}


void CmdWriteReg(USBReceiveData const * const commandPackage)
{
    // Parameters for SPI packages and variable to store output data
    USBTransmitData packageToSend;
    uint16 address;
    uint32 data;
    SPIReceiveData dataRecived;
    enum RWFlag rwOption = WRITE;
    uint16 length = 1;
    boolean isSuccessfulFlag = FALSE;

    // Unpack received data to variables
    address = ConstructWordFromBytes(commandPackage->data[1], commandPackage->data[0]);
    data = ConstructWordFromBytes(commandPackage->data[3], commandPackage->data[2]);

    // Send data to SPI with waiting for response
    isSuccessfulFlag = QSPIReadWriteSequence(&address, &data, &rwOption, &length);

    // Construct package to PC
    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);

    // Construct packages based on error status
    if (isSuccessfulFlag == FALSE)
    {
        // Common error frame setup
        packageToSend.status = USB_STATUS_ERROR;
        packageToSend.dataLength = 0;

        // Check if SPI response frame was received
        if (length > 0)
        {
            // Fill data in error frame with invalid response from CS600
            packageToSend.dataLength = 4;
            packageToSend.data[0] = GetByteByIdx(0, data);
            packageToSend.data[1] = GetByteByIdx(1, data);
            packageToSend.data[2] = GetByteByIdx(2, data);
            packageToSend.data[3] = GetByteByIdx(3, data);
        }
    }
    else
    {
        // Store SPI response frame to temporary variable for extracting data
        dataRecived.dw = data;

        packageToSend.status = USB_STATUS_DATA;
        packageToSend.dataLength = 2;
        packageToSend.data[0] = GetLSB(dataRecived.bf.output_data);
        packageToSend.data[1] = GetMSB(dataRecived.bf.output_data);
    }

    // Send data back to MCU
    SendUSBPackage(&packageToSend);
    ToggleLED4();
}

void CmdReadReg(USBReceiveData const * const commandPackage)
{
    // Parameters for SPI packages and variable to store output data
    USBTransmitData packageToSend;
    uint16 address;
    uint32 data;
    SPIReceiveData dataRecived;
    enum RWFlag rwOption = READ;
    uint16 length = 1;
    boolean isSuccessfulFlag = FALSE;

    // Unpack received data to variables
    address = ConstructWordFromBytes(commandPackage->data[1], commandPackage->data[0]);

    // Send data to SPI with waiting for response
    isSuccessfulFlag = QSPIReadWriteSequence(&address, &data, &rwOption, &length);

    // Construct package to PC
    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);

    // Construct packages based on error status
    if (isSuccessfulFlag == FALSE)
    {
        // Common error frame setup
        packageToSend.status = USB_STATUS_ERROR;
        packageToSend.dataLength = 0;

        // Check if SPI response frame was received
        if (length > 0)
        {
            // Fill data in error frame with invalid response from CS600
            packageToSend.dataLength = 4;
            packageToSend.data[0] = GetByteByIdx(0, data);
            packageToSend.data[1] = GetByteByIdx(1, data);
            packageToSend.data[2] = GetByteByIdx(2, data);
            packageToSend.data[3] = GetByteByIdx(3, data);
        }
    }
    else
    {
        // Store SPI response frame to temporary variable for extracting data
        dataRecived.dw = data;

        packageToSend.status = USB_STATUS_DATA;
        packageToSend.dataLength = 5;
        packageToSend.data[0] = dataRecived.bf.gen_status;
        packageToSend.data[1] = dataRecived.bf.s_bit;
        packageToSend.data[2] = dataRecived.bf.sid_add_status;
        packageToSend.data[3] = GetLSB(dataRecived.bf.output_data);
        packageToSend.data[4] = GetMSB(dataRecived.bf.output_data);

    }

    // Send data back to MCU
    SendUSBPackage(&packageToSend);
}

void CmdWriteRegRaw(USBReceiveData const * const commandPackage)
{
    // Parameters for SPI packages and variable to store output data
    USBTransmitData packageToSend;
    uint16 address;
    uint32 data;
    enum RWFlag rwOption = WRITE;
    uint16 length = 1;
    boolean isSuccessfulFlag = FALSE;

    // Unpack received data to variables
    address = ConstructWordFromBytes(commandPackage->data[1], commandPackage->data[0]);
    data = ConstructWordFromBytes(commandPackage->data[3], commandPackage->data[2]);

    // Send data to SPI with waiting for response
    isSuccessfulFlag = QSPIReadWriteSequence(&address, &data, &rwOption, &length);

    // Construct package to PC
    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);

    // Construct packages based on error status
    if (isSuccessfulFlag == FALSE)
    {
        // Common error frame setup
        packageToSend.status = USB_STATUS_ERROR;
        packageToSend.dataLength = 0;

        // Check if SPI response frame was received
        if (length > 0)
        {
            // Fill data in error frame with invalid response from CS600
            packageToSend.dataLength = 4;
            packageToSend.data[0] = GetByteByIdx(0, data);
            packageToSend.data[1] = GetByteByIdx(1, data);
            packageToSend.data[2] = GetByteByIdx(2, data);
            packageToSend.data[3] = GetByteByIdx(3, data);
        }
    }
    else
    {
        packageToSend.status = USB_STATUS_DATA;
        packageToSend.dataLength = 4;
        packageToSend.data[0] = GetByteByIdx(0, data);
        packageToSend.data[1] = GetByteByIdx(1, data);
        packageToSend.data[2] = GetByteByIdx(2, data);
        packageToSend.data[3] = GetByteByIdx(3, data);
    }

    // Send data back to MCU
    SendUSBPackage(&packageToSend);
}

void CmdReadRegRaw(USBReceiveData const * const commandPackage)
{
    // Parameters for SPI packages and variable to store output data
    USBTransmitData packageToSend;
    uint16 address;
    uint32 data;
    SPIReceiveData dataRecived;
    enum RWFlag rwOption = READ;
    uint16 length = 1;
    boolean isSuccessfulFlag = FALSE;

    // Unpack received data to variables
    address = ConstructWordFromBytes(commandPackage->data[1], commandPackage->data[0]);

    // Send data to SPI with waiting for response
    isSuccessfulFlag = QSPIReadWriteSequence(&address, &data, &rwOption, &length);

    // Construct package to PC
    packageToSend.msg_id = SetResponseBit(commandPackage->msg_id);

    // Construct packages based on error status
    if (isSuccessfulFlag == FALSE)
    {
        // Common error frame setup
        packageToSend.status = USB_STATUS_ERROR;
        packageToSend.dataLength = 0;

        // Check if SPI response frame was received
        if (length > 0)
        {
            // Fill data in error frame with invalid response from CS600
            packageToSend.dataLength = 4;
            packageToSend.data[0] = GetByteByIdx(0, data);
            packageToSend.data[1] = GetByteByIdx(1, data);
            packageToSend.data[2] = GetByteByIdx(2, data);
            packageToSend.data[3] = GetByteByIdx(3, data);
        }
    }
    else
    {
        // Store SPI response frame to temporary variable for extracting data
        dataRecived.dw = data;

        packageToSend.status = USB_STATUS_DATA;
        packageToSend.dataLength = 4;
        packageToSend.data[0] = GetByteByIdx(0, data);
        packageToSend.data[1] = GetByteByIdx(1, data);
        packageToSend.data[2] = GetByteByIdx(2, data);
        packageToSend.data[3] = GetByteByIdx(3, data);
    }

    // Send data back to MCU
    SendUSBPackage(&packageToSend);
}
