/**********************************************************************************************************************
 * \file general_cmd.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef GENERAL_CMD_H_
#define GENERAL_CMD_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "common/usb_data_types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Handling IS_ALIVE command from PC
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdIsAlive(USBReceiveData const * const commandPackage);

/** \brief Handling GET MCU VERSION  command from PC
 *
 * \param commandPackage package with command, command not used
 * \returns 3 bytes for current Version VERSION_MAJOR VERSION_MINOR VERSION_PATCH
 */
void CmdGetMcuVersion(USBReceiveData const * const commandPackage);

/** \brief Handling GET MCU DATE  command from PC
 *
 * \param commandPackage package with command, command not used
 * \return 8 byte build date yyyymmdd
 */
void CmdGetMcuBuildDate(USBReceiveData const * const commandPackage);

/** \brief Handling GET MCU TIME  command from PC
 *
 * \param commandPackage package with command, command not used
 * \return 4 byte build time hhmm
 */
void CmdGetMcuBuildTime(USBReceiveData const * const commandPackage);

/** \brief Handling WRITE_REG command from PC
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdWriteReg(USBReceiveData const * const commandPackage);

/** \brief Handling USB_CMD_SPI_INSTRUCTION command from PC
 *
 * \param commandPackage package with spi_instruction and 16bit input data
 * \returns status flags and 16 bit output data
 */
void CmdSpiInstuction(USBReceiveData const * const commandPackage);

/** \brief Handling of command USB_CMD_READ_DEV_ID
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdGetDeviceId(USBReceiveData * commandPackage);

/** \brief Handling several types of command instructons
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void handleCmdInstr(USBReceiveData const * const commandPackage);

/** \brief Handling READ_REG command from PC
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void handleSpiInstr(USBTransmitData * packageToSend, USBReceiveData const * const commandPackage);

/** \brief Handling WRITE_REG_RAW command from PC
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdWriteRegRaw(USBReceiveData const * const commandPackage);

/** \brief Handling READ_REG_RAW command from PC
 *
 * \param commandPackage package with command
 * \return Nothing
 */
void CmdReadRegRaw(USBReceiveData const * const commandPackage);

#endif /* GENERAL_CMD_H_ */
