/**********************************************************************************************************************
 * \file watchdog.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef WATCHDOG_H_
#define WATCHDOG_H_
#define WD_RESP_ADDRESS 0x013
#define WD_CONFIG0_ADDRESS 0x010
#define WD_CONFIG1_ADDRESS 0x011
#define WD_TIME_WIN_ADDRESS 0x014
#define WD_REQU_ADDRESS 0x016
#define WD_RESPTIME_ADDRESS 0x012
#define WD_CFG_PACKAGE_LEN 4

#define REQU_OFFSET 0
#define REQU_READMASK 0xF //0b0000000000001111
#define REQU_WRITEMASK 0xFFF0 //0b1111111111110000
#define RESP_CNT_OFFSET 14
#define RESP_CNT_READMASK 0x4000 //0b0100000000000000

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Platform_Types.h"
#include "common/usb_data_types.h"
#include "common/spi_data_types.h"
#include "common/command_queue.h"
#include "common/bit_manipulation.h"
#include "top/spi_wrapper.h"
#include "top/usb_wrapper.h"
#include "periphery/timer.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Function to configure CS600 Watchdog with config values from GUI's Watchdog tab and enable Watchdog
 * Corresponds to USB command USB_CMD_CONFIGURE_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdConfigureWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to get values of Watchdog config registers from CS600, and send them to PC to populate corresponding GUI fields
 * Corresponds to USB command USB_CMD_GET_CONFIG_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdGetConfigWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to start serving CS600 Watchdog's requests by MCU
 * Corresponds to USB command USB_CMD_START_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdStartWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to disable CS600 Watchdog's serving by MCU
 * Corresponds to USB command USB_CMD_STOP_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdStopWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to enable MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI
 * Corresponds to USB command USB_CMD_START_OBSERVATION_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdStartMonitoringWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to disable MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI
 * Corresponds to USB command USB_CMD_STOP_MONITORING_WATCHDOG
 *
 * \param commandPackage package with command
 * \return Returns nothing
 */
void CmdStopMonitoringWatchdog(USBReceiveData const * const commandPackage);

/** \brief Function to serve CS600 Watchdog's request
 * Corresponds to Internal command INT_CMD_ACK_WATCHDOG
 * \return Returns nothing
 */
void IntCmdServeWatchdog(void);

/** \brief Function that provides a Response word corresponding to Watchdog Request value
 * \param requValue Watchdog Request value
 * \param respWrdNumber Requested Response word (WORD_1 or WORD_0)
 * \return Response word value
 */
uint16 GetResponseWord(uint8 requValue, boolean respWrdNumber);

/** \brief Function that reads value of RESP_CNT field from CS600 WD_REQU register by SPI
 * \return Value of RESP_CNT field
 */
uint8 GetRespCnt(void);

/** \brief Function that reads value of REQU field from CS60 WD_REQU register by SPI
 * \return Value of REQU field
 */
uint8 GetREQUValue(void);

/** \brief Function that calculates periodicity of Watchdog serving procedure
 * \return Period duration of Watchdog serving procedure, in General Timer's interrupts
 */
uint16 CalculateWatchdogAckPeriodicity(void);

#endif /* WATCHDOG_H_ */

