/**********************************************************************************************************************
 * \file bit_manipulation.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef BIT_MANIPULATION_H_
#define BIT_MANIPULATION_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Construct word from 2 bytes
 *
 * \param msb MSB byte of the word
 * \param lsb LSB byte of the word
 * \return Constructed word
 */
uint16 ConstructWordFromBytes(uint8 msb, uint8 lsb);

/** \brief Get MSB byte of the word
 *
 * \param word 16 bit word
 * \return MSB byte of the 16 bit word
 */
uint8 GetMSB(uint16 word);

/** \brief Get LSB byte of the word
 *
 * \param word 16 bit word
 * \return LSB byte of the 16 bit word
 */
uint8 GetLSB(uint16 word);

/** \brief Get byte from 32bit word by index
 *
 * \param byteIdx byte index in word (LSB - 0, MSB - 3)
 * \param word 32 bit word
 * \return Requested byte. If index of of range - 0
 */
uint8 GetByteByIdx(uint8 byteIdx, uint32 word);

/** \brief Set response bit (8th) in message ID field
 *
 * \param msgID message ID
 * \return Message ID with response bit set
 */
uint8 SetResponseBit(uint8 msgID);

#endif /* BIT_MANIPULATION_H_ */
