/**********************************************************************************************************************
 * \file command_queue.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
// #include <stdio.h> // for memset
#include "Ifx_Types.h"
#include "usb_data_types.h"
#include "command_queue.h"

#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

static queue_t g_msgQueue;                                                    /** \brief global message queue handle */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

// TODO: add check if 90% queue occupied . generate error frame for MCU

void QueueInit()
{
    g_msgQueue.head = 0;
    g_msgQueue.tail = 0;
    g_msgQueue.size = QUEUE_SIZE;
}

USBReceiveData QueueRead()
{
    // Disable all interrupts
    boolean interruptsState = disableInterrupts();

    USBReceiveData emptyPackage = { 0, 0, 0 };
    USBReceiveData handle;
    handle.command = _USB_CMD_MAX;
    if (g_msgQueue.tail == g_msgQueue.head)
    {
        return handle;
    }
    handle = g_msgQueue.data[g_msgQueue.tail];
    g_msgQueue.data[g_msgQueue.tail] = emptyPackage;
    g_msgQueue.tail = (g_msgQueue.tail + 1) % g_msgQueue.size;

    // Reenable interrupts
    restoreInterrupts(interruptsState);

    return handle;
}

boolean QueueWrite(USBReceiveData const * const handle)
{
    // Disable all interrupts
    boolean interruptsState = disableInterrupts();

    if (((g_msgQueue.head + 1) % g_msgQueue.size) == g_msgQueue.tail)
    {
        return FALSE;
    }
    g_msgQueue.data[g_msgQueue.head] = *handle;
    g_msgQueue.head = (g_msgQueue.head + 1) % g_msgQueue.size;

    // Reenable interrupts
    restoreInterrupts(interruptsState);

    return TRUE;
}

boolean QueueWriteTail(USBReceiveData const * const handle)
{
    // Disable all interrupts
    boolean interruptsState = disableInterrupts();

    uint8 newTailPos = (g_msgQueue.tail == 0) ? (g_msgQueue.size - 1) : (g_msgQueue.tail - 1);
    if (g_msgQueue.head == newTailPos)
    {
        return FALSE;
    }
    g_msgQueue.data[newTailPos] = *handle;
    g_msgQueue.tail = newTailPos;

    // Reenable interrupts
    restoreInterrupts(interruptsState);

    return TRUE;
}

uint8 QueueGetOccupiedSize()
{
    // Disable all interrupts
    boolean interruptsState = disableInterrupts();

    uint8 occupiedSize;
    if (g_msgQueue.tail == g_msgQueue.head)
    {
        occupiedSize = 0;
    }
    else if (g_msgQueue.head > g_msgQueue.tail)
    {
        occupiedSize = g_msgQueue.head - g_msgQueue.tail;
    }
    else if (g_msgQueue.head < g_msgQueue.tail)
    {
        occupiedSize = (g_msgQueue.size - g_msgQueue.tail) + g_msgQueue.head;
    }

    // Reenable interrupts
    restoreInterrupts(interruptsState);

    return occupiedSize;
}

void QueueClear()
{
    // Disable all interrupts
    boolean interruptsState = disableInterrupts();

    g_msgQueue.head = 0;
    g_msgQueue.tail = 0;

    // Reenable interrupts
    restoreInterrupts(interruptsState);
}
