/**********************************************************************************************************************
 * \file command_queue.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef COMMAND_QUEUE_H_
#define COMMAND_QUEUE_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "usb_data_types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define QUEUE_SIZE  (17)                  /** \brief Queue size in frames (1 is unused due to queue implementation)  */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Structure for command queue (FIFO)
 */
typedef struct
{
    uint8 head;                         /** \brief data array index to add new record */
    uint8 tail;                         /** \brief data array index to read record */
    uint8 size;                         /** \brief data size (allocated, not occupied) */
    USBReceiveData data[QUEUE_SIZE];    /** \brief array with records of queue*/
} queue_t;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Initialize queue variable with default data
 */
void QueueInit();

/** \brief Read item from queue tail (first out) and remove it from queue
 *
 * \return Item from queue tail
 */
USBReceiveData QueueRead();

/** \brief Write item to queue head (first in)
 *
 * \param handle data to enqueue
 * \return True if possible to enqueue item, false if queue is full
 */
boolean QueueWrite(USBReceiveData const * const handle);

/** \brief Write item to queue tail (first out)
 * Required for fast response to command - ex. watchdog ack
 * (command will be executed immediately after current one finished)
 *
 * \param handle data to enqueue
 * \return True if possible to enqueue item, false if queue is full
 */
boolean QueueWriteTail(USBReceiveData const * const handle);

/** \brief Get occupied queue length
 *
 * \return Number of items in queue
 */
uint8 QueueGetOccupiedSize();

/** \brief Remove all items from queue
 */
void QueueClear();

#endif /* COMMAND_QUEUE_H_ */
