/**********************************************************************************************************************
 * \file crc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

uint8 CRC8(uint8 * const buffer, uint16 length)
{
    uint8 crc = 0x00; // initial value
    for (uint16 i = 0; i < length; i++)
    {
        crc ^= buffer[i];
        for (uint8 j = 0; j < 8; j++)
        {
            if ((crc & 0x80) != 0)
            {
                crc = (uint8)((crc << 1) ^ 0x7); // polynomial (MSB not included)
            }
            else
            {
                crc <<= 1;
            }
        }
    }
    crc ^= 0x55; // final XOR
    return crc;
}

uint8 CRC5(const uint32 buffer)
{
    uint8 crc;
    uint8 invertIt;
    uint8 length = 27; // length of data in bits, fixed value for SPI protocol

    // store initialization value into register
    crc = 0x1F;

    // calculate CRC as in specification
    // CRC polynomial: x^5 + x^2 + 1
    // - process bits from MSB to LSB
    // - XOR bits according to polynomial
    for (sint8 i = (length - 1); i >= 0; i--)
    {
        // process actual bit - save result of XOR of buffer bit and crc's 5th bit in a variable
        invertIt = ((buffer >> i) & 1) ^ ((crc & 0x10) >> 4);

        crc <<= 1;              // shift bits left
        crc &= 0x1E;            // clear 1st bit and bits > 5th
        crc |= invertIt;        // set 1st bit to value of processed bit from buffer
        crc ^= (invertIt << 2); // perform XOR operation on 2nd bit with value of processed bit from buffer
    }

    return crc;
}


/* generate the CRC3 for AB12 chip for Master Out Data
 *
 * The airbag system ASIC SPI is protected with a 3 bit CRC for the incoming data (bits 31 to 5
    included) and with a 3 bit CRC for the outgoing data (bits 26 to 3 included). For the incoming data
    the CRC is generated inside the uc and checked inside the airbag system ASIC to be consistent.
    For the outgoing data the CRC is generated inside the airbag system ASIC and can be checked
    within the uc.
    The CRC is generated by using the polynomial X3 + X + 1 with the binary start value “111”:
    The data word is fed (MSB first) into the shift registers of the CRC check and is supplemented
    with three leading zeros. In case of a CRC error within the incoming data, the last CRC bit of the
    outgoing data will be inverted


start_bit_crc = 31
end_bit_crc = 5
leading_zeros = 3

if (leading_zeros > end_bit_crc)
    --> Assertion: we would shift out relevant bit!
else

    buffer = buffer >> leading_zeros // include the leading zeros in crc rounding


length = start_bit_crc - end_bit_crc + 1 + leading_zeros // we iterate trough number of relevant bit + leading zeros



 * */
uint8 CRC3MO(const uint32 buffer)
{
    volatile uint32 mod_buffer = 0;// prvent optimizing out
    volatile uint32 processed_bit_from_buffer = 0;
    //uint32 mod_buffer = 0;
    uint8 crc;
    uint8 bit0 = 0;
    uint8 bit1 = 0;
    uint8 bit2 = 0;
    uint8 start_bit_crc = 31;
    uint8 end_bit_crc = 5;
    uint8 leading_zeros = 3;
    uint8 loop_end ;


    if (leading_zeros > end_bit_crc)
    {
        //  --> Assertion: we would shift out relevant bit!
    }
    else
    {
        mod_buffer = buffer >> leading_zeros; // include the leading zeros in the buffer
        // make sure to shift only zeros in!
    }

    // loop troug all relevant bit , from startbit  to endbit, including the leading zeros into the loop!
    loop_end = end_bit_crc - leading_zeros; // endbit = 5 leading zeros = 3 --> lopp_end = 1


    // TODO: make sure that msb is rightmost pos.

    // store binary start value "111" into register according spec
    crc = 0x07;

    // calculate CRC as in specification
    // CRC polynomial: x^3 + x + 1 --> 1*x^3 + 0* x^2 + 1*x^1 1*x^0 --> poly = 1011
    // - process bits from start_bit_crc  to end_bit_crc, MSb first
    // - XOR bits according to polynomial
    for (sint8 i = start_bit_crc; i >= loop_end ; i--)
    {
        // process bit 0: crc_bit 3 old Xor with MSb from buffer
        bit0 = ((crc & 0x04) >> 2) ^ ((mod_buffer >> i) & 1);
        // process bit 1: crc_bit 3 old Xor with crc_bit_1 old
        bit1 = ((crc & 0x01) << 1)  ^ ((crc & 0x04) >> 1);
        // bit 2 = bit1_old
        bit2 = ((crc & 0x02) << 1);

        crc = bit2 | bit1 | bit0 ;            // set new crc

        // create a buffer with all processed bits for debugging
        processed_bit_from_buffer |= (uint32)(0x01 << i);
    }

    return crc;
}

uint8 CRC3MI(const uint32 buffer)
{
    volatile uint32 mod_buffer = 0;// prvent optimizing out
    volatile uint32 processed_bit_from_buffer = 0;
    //uint32 mod_buffer = 0;
    uint8 crc;
    uint8 bit0 = 0;
    uint8 bit1 = 0;
    uint8 bit2 = 0;
    uint8 start_bit_crc = 26;
    uint8 end_bit_crc = 3;
    uint8 leading_zeros = 3;
    uint8 loop_end ;


    if (leading_zeros > end_bit_crc)
    {
        //  --> Assertion: we would shift out relevant bit!
    }
    else
    {
        mod_buffer = buffer >> leading_zeros; // include the leading zeros in the buffer
        // make sure to shift only zeros in!
    }

    // loop troug all relevant bit , from startbit  to endbit, including the leading zeros into the loop!
    loop_end = end_bit_crc - leading_zeros; // endbit = 5 leading zeros = 3 --> lopp_end = 1


    // TODO: make sure that msb is rightmost pos.

    // store binary start value "111" into register according spec
    crc = 0x07;

    // calculate CRC as in specification
    // CRC polynomial: x^3 + x + 1 --> 1*x^3 + 0* x^2 + 1*x^1 1*x^0 --> poly = 1011
    // - process bits from start_bit_crc  to end_bit_crc, MSb first
    // - XOR bits according to polynomial
    for (sint8 i = start_bit_crc; i >= loop_end ; i--)
    {
        // process bit 0: crc_bit 3 old Xor with MSb from buffer
        bit0 = ((crc & 0x04) >> 2) ^ ((mod_buffer >> i) & 1);
        // process bit 1: crc_bit 3 old Xor with crc_bit_1 old
        bit1 = ((crc & 0x01) << 1)  ^ ((crc & 0x04) >> 1);
        // bit 2 = bit1_old
        bit2 = ((crc & 0x02) << 1);

        crc = bit2 | bit1 | bit0 ;            // set new crc

        // create a buffer with all processed bits for debugging
        processed_bit_from_buffer |= (uint32)(0x01 << i);
    }

    return crc;
}


