/**********************************************************************************************************************
 * \file crc.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef CRC_H_
#define CRC_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Calculate CRC (CRC-8-CCITT, -ITU)
 * Polynom: x^8+x^2+x+1
 *
 * \param buffer pointer to buffer with data to calculate CRC
 * \param length number of bytes to use for calculation
 * \return Returns CRC
 */
uint8 CRC8(uint8 * const buffer, uint16 length);

/** \brief Calculate CRC (CRC-5-USB)
 * Polynom: x^5+x^2+x+1
 *
 * \param buffer buffer with data to calculate CRC
 * \param length number of bits to use for calculation
 * \return Returns CRC
 */
uint8 CRC5(const uint32 buffer);

/** \brief Calculate CRC for master output () TODO: needs refactoring. Notes in .c file
 * Polynom: x^3 + x + 1 
 *
 * \param buffer buffer with data to calculate CRC
 * \param length number of bits to use for calculation
 * \return Returns CRC
 */
uint8 CRC3MO(const uint32 buffer);

/** \brief Calculate CRC for master input () TODO: needs refactoring. Notes in .c file
 * Polynom: x^3 + x + 1 
 *
 * \param buffer buffer with data to calculate CRC
 * \param length number of bits to use for calculation
 * \return Returns CRC
 */
uint8 CRC3MI(const uint32 buffer);


#endif /* CRC_H_ */
