/**************************************************************************************************************************
 * \file usb_data_types.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *************************************************************************************************************************/

#ifndef USB_DATA_TYPES_H_
#define USB_DATA_TYPES_H_

/*************************************************************************************************************************/
/*-----------------------------------------------------Includes----------------------------------------------------------*/
/*************************************************************************************************************************/

#include "Ifx_Types.h"

/*************************************************************************************************************************/
/*------------------------------------------------------Macros-----------------------------------------------------------*/
/*************************************************************************************************************************/

#define MAX_USB_CMD_LENGTH              (1)                          /** \brief Max USB command length in bytes          */
#define MAX_USB_RECIEVE_PAYLOAD_LENGTH  (64)                         /** \brief Max USB payload length in bytes          */
#define MAX_USB_TRANSMIT_PAYLOAD_LENGTH (128)                        /** \brief Max USB payload length in bytes          */
#define MAX_USB_CRC_LENGTH              (1)                          /** \brief Max USB crc length in bytes              */
#define MAX_USB_PACKAGE_LENGTH          (1 + 1 + MAX_USB_CMD_LENGTH + \
                                         1 + MAX_USB_TRANSMIT_PAYLOAD_LENGTH + \
                                         MAX_USB_CRC_LENGTH + 1)     /** \brief Max USB package length in bytes          */
#define MIN_USB_MSG_LENGTH              (7)                          /** \brief Min USB message length in bytes          */

#define USB_MSG_ID_POS                  (1)                          /** \brief USB MSG_ID field posstion in package     */
#define USB_ASIC_ID_POS                 (2)                          /** \brief USB CMD ASIC ID  position in package */
#define USB_CMD_STAT_POS                (3)                          /** \brief USB CMD/STATUS field position in package */
#define USB_PAYLOAD_LEN_POS             (4)                          /** \brief USB PAYLOAD LEN field position in package*/
#define USB_PAYLOAD_POS                 (5)                          /** \brief USB PAYLOAD field position in package    */

#define USB_RESERVED_ID_1               (0x20)                       /** \brief Reserved ID for MCU messages             */
#define USB_RESERVED_ID_2               (0x21)                       /** \brief Reserved ID for MCU messages             */

/*************************************************************************************************************************/
/*--------------------------------------------------Enumerations---------------------------------------------------------*/
/*************************************************************************************************************************/

/** \brief Defines applicable commands for received USB data
 * Includes min and max command
 */
typedef enum
{
    _USB_CMD_MIN                        = 0,                  /** \brief minimal value of command (not included) */

    USB_CMD_IS_ALIVE                    = 1,                  /** \brief transaction to check if USB communication works */
    USB_CMD_SPI_INSTRUCTION             = 2,                  /** \brief execute SPI instruction with 16bit input data (send via payload) */
//   USB_CMD_READ_DEV_ID                 = 3,                  /** \brief reads ASIC Device ID, reports error if unsuccessful */
//    USB_CMD_READ_REG_RAW                = 4,                  /** \brief read single register, otput data in raw format, reports error if unsuccessful */
//    USB_CMD_WRITE_REG_RAW               = 5,                  /** \brief write single register, otput data in raw format, reports error if unsuccessful */
//    USB_CMD_ABORT                       = 6,                  /** \brief stops current operation TODO: clear definition of behavior */
//    USB_CMD_STOP_READING                = 7,                  /** \brief stop reading sequence */
//    USB_CMD_STOP_WATCHDOG               = 8,                  /** \brief stop to perform periodic Watchdog Request acknowledgement by MCU */
//    USB_CMD_STOP_GPIO_READING           = 9,                  /** \brief stop reading MCU GPIO pins */
//    USB_CMD_STOP_READ_ERRORS            = 10,                  /** \brief stop reading error registers */
//    USB_CMD_EXECUTE_RW_SEQUENCE         = 11,                 /** \brief perform single read/write series of operation */
//    USB_CMD_EXECUTE_READ_SEQUENCE       = 12,                 /** \brief perform single read series operation */
//    USB_CMD_EXECUTE_WRITE_SEQUENCE      = 13,                 /** \brief perform single write series operation */
//    USB_CMD_CONFIGURE_READING           = 14,                 /** \brief reconfigure continuos reading (table, periodiciyr, etc.) */
//    USB_CMD_CONFIGURE_WATCHDOG          = 15,                 /** \brief configure watchdog (Note: initiates read/write seq, configs timer, arms watchdog response) */
//    USB_CMD_START_READING               = 16,                 /** \brief start reading defined set of registers */
//    USB_CMD_START_WATCHDOG              = 17,                 /** \brief start to perform periodic Watchdog Request acknowledgement by MCU  */
//    USB_CMD_START_GPIO_READING          = 18,                  /** \brief start reading MCU GPIO pins */
//    USB_CMD_START_READ_ERRORS           = 19,                 /** \brief start reading CS600 basic error registers */
//    USB_CMD_RESET_TO_IDLE               = 20,                 /** \brief stop all continuous operations, set all pins to default state, wait for new command */
//    USB_CMD_GET_CONFIG_WATCHDOG         = 21,                 /** \brief get values of Watchdog config registers from CS600, and send them to PC to populate corresponding GUI fields */
//    USB_CMD_START_MONITORING_WATCHDOG   = 22,                 /** \brief enables MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI; continuous command */
//    USB_CMD_STOP_MONITORING_WATCHDOG    = 23,                 /** \brief disables MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI */
//    USB_CMD_BYPASS_MCU                  = 24,                 /** \brief sets MCU to bypass mode (not interfering external MCU communication) */
//    USB_CMD_ACTIVATE_MCU                = 25,                 /** \brief activates MCU, exits from bypass mode */
    USB_CMD_GET_MCU_VERSION              = 26,                 /** \brief returns MCU SW version */
    USB_CMD_GET_MCU_BUILD_DATE           = 27,                 /** \brief returns MCU SW build date */
    USB_CMD_GET_MCU_BUILD_TIME           = 28,                 /** \brief returns MCU SW build time */

    _USB_EXT_CMD_MAX                    = 63,                 /** \brief maximal value of command send via USB, start of internal commands (generated by MCU) */

    INT_CMD_SYS_TIMER_UPD               = 64,                 /** \brief execute system timer sequence */
    INT_CMD_ACK_WATCHDOG                = 65,                 /** \brief acknowlege CS600 watchdog */
    INT_CMD_CS600_ERR_CHECK             = 66,                 /** \brief check if any error in CS600 main error registers */
    INT_CMD_CONT_READ                   = 67,                 /** \brief execute one iteration of continuous read */
    INT_CMD_GPIO_READ                   = 68,                 /** \brief execute one iteration of MCU + CS600 GPIO read */

    _USB_CMD_MAX                        = 127                 /** \brief maximal value of command (not included) */
} USBCommandsEnum;

/** \brief Defines applicable statuses for transmitted USB data
 * Includes min and max status
 */
typedef enum
{
    _USB_STATUS_MIN                    = 127,             /** \brief minimal value of status (not included) */

    USB_STATUS_ACK                     = 128,             /** \brief response to is alive transaction */
    USB_STATUS_ERROR                   = 129,             /** \brief error at MCU or CS600, data holds error info */
    USB_STATUS_ERROR_TELEMETRY         = 130,             /** \brief error telemetry data of CS600 and MCU */
    USB_STATUS_STATUS                  = 131,             /** \brief status of MCU, data holds status info/log */
    USB_STATUS_BUSY                    = 132,             /** \brief MCU is busy processing previous command TODO: check if required */
    USB_STATUS_DATA                    = 133,             /** \brief response to read or read/write transaction (also works for transactions including such behaviour) */
    //TODO: Implement
    USB_STATUS_CMD_NO_SUPPORTED        = 134,             /** \brief response if cmd is not supported*/
    USB_STATUS_CMD_WRONG_PAYLOAD_LEN   = 135,             /** \brief response if cmd has wrong payload len*/
    // TODO: end
    _USB_STATUS_MAX                    = 255              /** \brief maximal value of command (not included) */
} USBStatusesEnum;

/*************************************************************************************************************************/
/*-------------------------------------------------Data Structures-------------------------------------------------------*/
/*************************************************************************************************************************/

/** \brief Structure for received USB data
 */
typedef struct
{
    uint8           msg_id;                                 /** \brief message ID */
    uint8           asic_id;                                /** \brief ASIC ID */
    USBCommandsEnum command;                                /** \brief command from PC */
    uint8           dataLength;                             /** \brief data length in bytes */
    uint8           data[MAX_USB_RECIEVE_PAYLOAD_LENGTH];   /** \brief array with payload */
} USBReceiveData;

/** \brief Structure for transmit USB data
 */
typedef struct
{
    uint8           msg_id;                                 /** \brief message ID */
    uint8           asic_id;                                /** \brief ASIC ID */
    USBStatusesEnum status;                                 /** \brief MCU status */
    uint8           dataLength;                             /** \brief data length in bytes */
    uint8           data[MAX_USB_TRANSMIT_PAYLOAD_LENGTH];  /** \brief array with payload */
} USBTransmitData;

/*************************************************************************************************************************/
/*------------------------------------------------Function Prototypes----------------------------------------------------*/
/*************************************************************************************************************************/

/*************************************************************************************************************************/
/*-------------------------------------------------Global variables------------------------------------------------------*/
/*************************************************************************************************************************/

#endif /* USB_DATA_TYPES_H_ */
