from typing import List
from typeguard import typechecked
from enum import Enum
from crc_helper import crc8
from package_constants import pkg_const

class Command(Enum):
    '''USB commands enumeration. Must be in sync with enumeration in firmware'''
    _MIN                        = 0              # minimal value of command (not included)
 
    IS_ALIVE                    = 1              # transaction to check if USB communication works
    SPI_INSTRUCTION             = 2              # execute SPI instruction with 16bit input data (send via payload)
    READ_DEV_ID                 = 3              # reads ASIC Device ID, reports error if unsuccessful
    READ_REG                    = 4              # read single register, otput data in raw format, reports error if unsuccessful
    WRITE_REG                   = 5              # write single register, otput data in raw format, reports error if unsuccessful
    CONFIGURE_READING           = 6              # reconfigure continuos reading (table, periodiciyr, etc.)
    START_READING_SEQ           = 7              # start reading defined set of registers
    STOP_READING_SEQ            = 8              # stop reading sequence
    STOP_WATCHDOG               = 9              # stop to perform periodic Watchdog Request acknowledgement by MCU
    EXECUTE_RW_SEQUENCE         = 10             # perform single read/write series of operation
    EXECUTE_READ_SEQUENCE       = 11             # perform single read series operation
    EXECUTE_WRITE_SEQUENCE      = 12             # perform single write series operation
    CONFIGURE_WATCHDOG          = 13             # configure watchdog (Note: initiates read/write seq, configs timer, arms watchdog response)
    START_WATCHDOG              = 14             # start to perform periodic Watchdog Request acknowledgement by MCU  
    RESET_TO_IDLE               = 15             # stop all continuous operations, set all pins to default state, wait for new command
    START_MONITORING_WATCHDOG   = 16             # enables MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI; continuous command
    STOP_MONITORING_WATCHDOG    = 17             # disables MCU functionality that sends values of Watchdog status registers and time durations between the polls to GUI
    GET_MCU_VERSION             = 18             # returns MCU SW version
    GET_MCU_BUILD_DATE          = 19             # returns MCU SW build date
    GET_MCU_BUILD_TIME          = 20             # returns MCU SW build time
    SET_EXT_OSC_2MHZ            = 21             # sets external clock output to 2Mhz
    SET_EXT_OSC_4MHZ            = 22             # sets external clock output to 4Mhz  
    FLM_DIAG_ENABLE             = 23             # enables Firing Loop Module cyclic diagnostics TODO: should be verified after feature merging
    FLM_DIAG_READ_RESULTS       = 24             # returns results of Firing Loop Module cyclic diagnostics TODO: should be verified after feature merging
    INIT_SYNC                   = 25             # syncs ASIC and GUI: SPI_COLDSTART_1, response to GUI when ASIC in INIT state TODO: should be verified after feature merging
    WRITE_RAW_DATA_SPI          = 26             # 0x1A write 32bit raw data to spi
    FLM_DIAG_DISABLE            = 27             # enables Firing Loop Module cyclic diagnostics TODO: should be verified after feature merging
    
    START_TEST_MODE1            = 29             # configure and start Test mode 1 
    START_TEST_MODE2            = 30             # configure and start Test mode 1 
    STOP_TEST_MODE12            = 31             # stop Test mode (currently running) 
   
    _USB_EXT_CMD_MAX            = 63             # maximal value of command send via USB, start of internal commands (generated by MCU)
 
    INT_CMD_SYS_TIMER_UPD       = 64             # execute system timer sequence
    INT_CMD_ACK_WATCHDOG1       = 65             # acknowlege watchdog 1
    INT_CMD_ACK_WATCHDOG2       = 66             # acknowlege watchdog 2
    INT_CMD_READ_WD_STATUS      = 67             # read watchdogs status registers
 
    _MAX                        = 127            # maximal value of command (not included)

class Status(Enum):
    '''USB statuses enumeration. Must be in sync with enumeration in firmware'''
    _MIN                        = 127            # minimal value of status (not included) 
 
    ACK                         = 128            # response to is alive transaction 
    ERROR                       = 129            # error at MCU or CS600, data holds error info 
    ERROR_TELEMETRY             = 130            # error telemetry data of CS600 and MCU 
    STATUS                      = 131            # status of MCU, data holds status info/log 
    BUSY                        = 132            # MCU is busy processing previous command
    DATA                        = 133            # response to read or read/write transaction (also works for transactions including such behaviour) 
    RESPONSE_ABSENT             = 134            # response from MCU hasn't been received in expected timeframe 
    CMD_NO_SUPPORTED            = 135            # response if cmd is not supported
    CMD_WRONG_PAYLOAD_LEN       = 136            # response if cmd has wrong payload len
    
    _MAX                        = 255            # maximal value of command (not included) 

@typechecked
class TransmitPackage(): #metaclass=MultipleMeta
    '''Wrapper for packages from PC to MCU'''

    def __init__(self, msg_id:int=0, device_id:int=0, cmd:Command=Command._MIN, payload:List[int]=[]):
        self.msg_id = msg_id
        self.device_id = device_id
        self.cmd = cmd.value
        self.payload_len = len(payload)
        self.payload = payload

    def validate_package(self):
        if ((self.msg_id < 0) or (self.msg_id >= 0x80)):
            raise Exception("MessageID has incorrect value")
        if ((self.device_id < 0) or (self.device_id > 11)):
            raise Exception("ASIC index has incorrect value")
        if (self.payload_len > 0xFF):
            raise Exception("Payload length is too big")

    def serialize(self) -> bytes:
        '''Get package as list of bytes (ints)'''
        self.validate_package()
        package_array = [pkg_const.START_BYTE_VALUE, self.msg_id, self.device_id, self.cmd, self.payload_len, *self.payload]
        package_array.append(crc8(package_array, pkg_const.MSG_ID_POSITION, (len(package_array)-pkg_const.END_BYTE_LENGTH)))
        package_array.append(pkg_const.END_BYTE_VALUE)
        return bytes(package_array)

@typechecked
class ReceivePackage():
    '''Wrapper for packages from MCU to PC'''

    def __init__(self, package:List[int]):
        self.package = package
        self.unpack()

    def unpack(self):
        self.start_byte  = self.package[pkg_const.START_BYTE_POSITION]
        self.msg_id      = self.package[pkg_const.MSG_ID_POSITION]
        self.device_id     = self.package[pkg_const.ASIC_ID_POSITION]
        self.status      = Status(self.package[pkg_const.CMD_STATUS_POSITION])
        self.payload_len = self.package[pkg_const.PAYLOAD_LENGTH_POSITION]
        self.payload     = list(self.package[pkg_const.PAYLOAD_POSITION : (pkg_const.PAYLOAD_POSITION + self.payload_len)])
        self.crc         = self.package[pkg_const.PAYLOAD_POSITION+self.payload_len]
        self.stop_byte   = self.package[pkg_const.PAYLOAD_POSITION+self.payload_len+pkg_const.CRC_LENGTH]

        self.validate_package()

    def validate_package(self):
        if (self.start_byte != pkg_const.START_BYTE_VALUE):
            raise Exception("Start byte value is wrong")
        if (self.crc != crc8(self.package, pkg_const.MSG_ID_POSITION, len(self.package) - pkg_const.START_BYTE_LENGTH - pkg_const.CRC_LENGTH - pkg_const.END_BYTE_LENGTH)):
            raise Exception("CRC value is incorrect")
        if ((self.msg_id < 0x80) or (self.msg_id >= 0xFF)):
            raise Exception("MessageID has incorrect value")
        if ((self.device_id < 0) or (self.device_id > 11)):
            raise Exception("ASIC index has incorrect value")
        if (self.payload_len > 0xFF):
            raise Exception("Payload length is too big")
        if (self.stop_byte != pkg_const.END_BYTE_VALUE):
            raise Exception("Stop byte value is wrong")

@typechecked
class Int2BytesConverter():
    '''Class to get individual bytes from int'''

    def __init__(self, value:int):
        # Precondition
        if ((value > 0xFFFF) or (value < 0x0000)):
            assert False, "Incorrect input for int to byte converter"

        self.value = value

        # Fields to get individual bytes
        self.byte0 =  value & 0xFF
        self.byte1 = (value & 0xFF00) >> 8

        # As array
        self.bytes = [self.byte0, self.byte1]

@typechecked
class Bytes2IntConverter():
    '''Class to get int from individual bytes'''

    def __init__(self, value_list:List[int]):
        # Precondition
        for itm in value_list:
            if ((itm > 0xFF) or (itm < 0x00)):
                assert False, "Incorrect input for byte to int converter"
        if len(value_list) != 2:
            assert False, "Unexpected package length"

        # Main code
        self.value_list = value_list
        self.int_value = 0

        for idx, itm in enumerate(value_list):
            self.int_value |= itm << (idx * 8)


# Selftest + usage example
if __name__ == "__main__":
    package = TransmitPackage(0x0F, 1, Command.READ_DEV_ID, []) # example with READ_DEV_ID command
    test = package.serialize()

    package2 = ReceivePackage([0xAB, 0x80, 0x0, 0x83, 0x3, 0x0, 0x2, 0x0, 0xFE, 0xBA]) # example with GET_MCU_BUILD_VERSION response

    package3 = TransmitPackage()

