/**********************************************************************************************************************
 * \file crc_wrapper.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "common/usb_data_types.h"
#include "common/spi_data_types.h"
#include "common/crc.h"

#include "crc_wrapper.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

boolean IsCRC8Correct(uint8 * const data, uint16 length, uint8 expectedCrc)
{
    uint8 calculatedCRC = 0;
    boolean result = FALSE;
    if (data != NULL_PTR)
    {
        calculatedCRC = CRC8(data, length);
        result = (expectedCrc == calculatedCRC) ? (TRUE) : (FALSE);
    }

    return result;
}

boolean IsCRC5Correct(SPIReceiveData * const data)
{
    uint8 calculatedCRC = 0;
    boolean result = FALSE;
    uint8 expectedCrc = data->bf.crc;
    uint32 twentySevenBitData = (data->dw) >> CRC5_LENGTH; // get only data from package without CRC

    calculatedCRC = CRC5(twentySevenBitData);
    result = (expectedCrc == calculatedCRC) ? (TRUE) : (FALSE);

    return result;
}

uint8 GetCRC8(uint8 * const data, uint16 length)
{
    uint8 calculatedCRC = 0;
    if (data != NULL_PTR)
    {
        calculatedCRC = CRC8(data, length);
    }
    return calculatedCRC;
}

uint8 GetCRC5(SPITransmitData * const data)
{
    uint8 calculatedCRC = 0;
    uint32 twentySevenBitData;
    if (data != NULL_PTR)
    {
        twentySevenBitData = (data->dw) >> CRC5_LENGTH;
        calculatedCRC = CRC5(twentySevenBitData);
    }
    return calculatedCRC;
}