/**********************************************************************************************************************
 * \file status.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "status.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*************************************************************************************************************************/
/*-------------------------------------------------Data Structures-------------------------------------------------------*/
/*************************************************************************************************************************/

/** \brief Structure for holding status data for MCU
 */
typedef union
{
    struct
    {
        uint32 state            : 4;    /** \brief state of MCU SW */
        uint32 usbError         : 1;    /** \brief error during USB communication occured */
        uint32 spiError         : 1;    /** \brief error during SPI communication occured */
        uint32 contReadState    : 2;    /** \brief continuous read feature state */
        uint32 errorCheckState  : 2;    /** \brief error check feature state */
        uint32 watchdogState    : 2;    /** \brief watchdog feature state */
        uint32 gpioState        : 2;    /** \brief gpio feature state */
        uint32 reserved         : 18;   /** \brief reserved bits */
    } bf;
    uint32 dw;
} StatusType;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

StatusType g_status;                              /** \brief Global status variable                                  */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void InitStatus(void)
{
    g_status.dw = 0;
}

uint32 GetStatus(void)
{
    return g_status.dw;
}

void SetState(MCUStatesEnum newState)
{
    g_status.bf.state = (uint8) newState;
}

boolean GetUSBError(void)
{
    return (g_status.bf.usbError == 1);
}

boolean GetSPIError(void)
{
    return (g_status.bf.spiError == 1);
}

void SetUSBError(void)
{
    g_status.bf.usbError = 1;
}

void SetSPIError(void)
{
    g_status.bf.spiError = 1;
}

void ClearUSBError(void)
{
    g_status.bf.usbError = 0;
}

void ClearSPIError(void)
{
    g_status.bf.spiError = 0;
}

ContinuousFeaturesStatesEnum GetContinuousReadState(void)
{
    return g_status.bf.contReadState;
}

ContinuousFeaturesStatesEnum GetErrorCheckState(void)
{
    return g_status.bf.errorCheckState;
}

ContinuousFeaturesStatesEnum GetWatchdogState(void)
{
    return g_status.bf.watchdogState;
}

ContinuousFeaturesStatesEnum GetGPIOState(void)
{
    return g_status.bf.gpioState;
}

void SetContinuousReadState(ContinuousFeaturesStatesEnum newState)
{
    g_status.bf.contReadState = (uint8) newState;
}

void SetErrorCheckState(ContinuousFeaturesStatesEnum newState)
{
    g_status.bf.errorCheckState = (uint8) newState;
}

void SetWatchdogState(ContinuousFeaturesStatesEnum newState)
{
    g_status.bf.watchdogState = (uint8) newState;
}

void SetGPIOState(ContinuousFeaturesStatesEnum newState)
{
    g_status.bf.gpioState = (uint8) newState;
}