/**********************************************************************************************************************
 * \file status.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef STATUS_H_
#define STATUS_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Defines applicable states for state field in global status
 */
typedef enum
{
    MCU_STATE_IDLE                  = 0,   /** \brief idle state, entered immediately after POR */
    MCU_STATE_CONFIGURED            = 1,   /** \brief configured state, initial configuration passed, in dispatcher loop */
    MCU_STATE_ERROR                 = 2    /** \brief error occurred */
} MCUStatesEnum;

/** \brief Defines applicable states for continuously running features
 */
typedef enum
{
    FEATURE_DISABLED    = 0,           /** \brief disabled state */
    FEATURE_CONFIGURED  = 1,           /** \brief configured state, feature is still disabled, but config received */
    FEATURE_RUNNING     = 2,           /** \brief execution of feature ongoing */
    FEATURE_ERROR       = 3            /** \brief error during feature execution occured */
} ContinuousFeaturesStatesEnum;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Initializes MCU status. All fields set to 0
 *
 * \return Returns nothing
 */
void InitStatus(void);

/** \brief Gets MCU status
 *
 * \return Returns MCU status
 */
uint32 GetStatus(void);

/** \brief Sets state of MCU SW execution
 *
 * \param newState new state of state field in status
 * \return Nothing
 */
void SetState(MCUStatesEnum newState);

/** \brief Gets USB communication error flag
 *
 * \return Returns TRUE is error flag set, FALSE - otherwise
 */
boolean GetUSBError(void);

/** \brief Gets SPI communication error flag
 *
 * \return Returns TRUE is error flag set, FALSE - otherwise
 */
boolean GetSPIError(void);

/** \brief Sets USB communication error flag
 *
 * \return Returns nothing
 */
void SetUSBError(void);

/** \brief Sets SPI communication error flag
 *
 * \return Returns nothing
 */
void SetSPIError(void);

/** \brief Clears USB communication error flag
 *
 * \return Returns nothing
 */
void ClearUSBError(void);

/** \brief Clears SPI communication error flag
 *
 * \return Returns nothing
 */
void ClearSPIError(void);

/** \brief Gets state of continuous read feature
 *
 * \return State
 */
ContinuousFeaturesStatesEnum GetContinuousReadState(void);

/** \brief Gets state of error check feature
 *
 * \return State
 */
ContinuousFeaturesStatesEnum GetErrorCheckState(void);

/** \brief Gets state of watchdog feature
 *
 * \return State
 */
ContinuousFeaturesStatesEnum GetWatchdogState(void);

/** \brief Gets state of GPIO feature
 *
 * \return State
 */
ContinuousFeaturesStatesEnum GetGPIOState(void);

/** \brief Sets state of continuous read feature
 *
 * \param newState new state of continuous read field in status
 * \return Nothing
 */
void SetContinuousReadState(ContinuousFeaturesStatesEnum newState);

/** \brief Sets state of error check feature
 *
 * \param newState new state of error check field in status
 * \return Nothing
 */
void SetErrorCheckState(ContinuousFeaturesStatesEnum newState);

/** \brief Sets state of watchdog feature
 *
 * \param newState new state of watchdog field in status
 * \return Nothing
 */
void SetWatchdogState(ContinuousFeaturesStatesEnum newState);

/** \brief Sets state of GPIO feature
 *
 * \param newState new state of watchdog field in status
 * \return Nothing
 */
void SetGPIOState(ContinuousFeaturesStatesEnum newState);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

#endif /* STATUS_H_ */
