/**********************************************************************************************************************
 * \file usb_wrapper.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"
#include "_Utilities/Ifx_Assert.h"
#include "common/usb_data_types.h"
#include "top/crc_wrapper.h"
#include "periphery/usb.h"

#include "top/usb_wrapper.h"

// for debugging commands JS 4/2024
#include "led.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define USB_START_BYTE          (0xAB)                          /** \brief USB start byte value                      */
#define USB_STOP_BYTE           (0xBA)                          /** \brief USB stop byte value                       */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void USBInit(void)
{
    InitUSBInterface();
}

boolean SendUSBPackage(const USBTransmitData * data)
{
    // Validate that data is not null pointer
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, data != NULL_PTR);

    // Initialize temporary variables
    uint8 buffer[MAX_USB_PACKAGE_LENGTH];
    Ifx_SizeT itemCounter = 0;

    // Fill buffer with package
    buffer[itemCounter] = USB_START_BYTE;             /* Start package byte  */
    itemCounter++;

    buffer[itemCounter] = data->msg_id;
    itemCounter++;

    buffer[itemCounter] = data->asic_id;
    itemCounter++;

    buffer[itemCounter] = data->status;
    itemCounter++;

    buffer[itemCounter] = data->dataLength; /*   Payload length   */
    itemCounter++;

    for (uint16 i = 0; i < data->dataLength; i++)
    {
        //
        buffer[itemCounter] = data->data[i]; /* Payload */
        itemCounter++;
    }

    buffer[itemCounter] = GetCRC8(&(buffer[1]), itemCounter-1); /*   CRC, ommit 1st byte   */
    itemCounter++;

    buffer[itemCounter] = USB_STOP_BYTE;             /* End package byte  */
    itemCounter++;

    // Check if enough space in UART buffer
    sint32 bytesLeft;
    do
    {
        // TODO : ["../top/usb_wrapper.c" 106/39] calling a function without a prototype
        bytesLeft = GetWriteBufferLeft();
    }
    while (bytesLeft < itemCounter);

    // Send package
    uint8 result = SendUSBData(buffer, &itemCounter);

    return result;
}

boolean ReceiveUSBPackage(USBReceiveData * const data)
{
    // Validate that data is not null pointer
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, data != NULL_PTR);

    // Initialize temporary variables
    static uint8 buffer[MAX_USB_PACKAGE_LENGTH] = {0};
    static Ifx_SizeT itemCounter = 0;
    static boolean previousReadNotFinished = FALSE;
    Ifx_SizeT tmpCounter = 1;
    volatile sint32 bytesIncoming;

    // Read beginning of package if previous read was finished
    if (previousReadNotFinished == FALSE)
    {
        // Return if no items in buffer
        if (IsInBufferEmpty()) return FALSE;

        // Clean buffer
        for (int i = 0; i < MAX_USB_PACKAGE_LENGTH; i++) buffer[i] = 0; // TODO: can be optimized

        // Start reading sequence
        // Read first byte of message
        ReceiveUSBData(buffer, &tmpCounter);

        // Verify that first byte of data is start byte
        if (buffer[0] != USB_START_BYTE)
        {
            IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, FALSE);

            //poll buffer[0] for start of message
            //Read buffer by byte till reach USB_START_BYTE
            while (buffer[0] != USB_START_BYTE)
            {
                // If read all buffer, but no required start byte - return
                if (IsInBufferEmpty()) return FALSE;

                tmpCounter = 1;
                ReceiveUSBData(buffer, &tmpCounter);
            }
        }
        // If encountered start byte - read remaining bytes till payload
        tmpCounter = 4; // TODO: remove magic numbers - number of items to read at first
        ReceiveUSBData(&(buffer[1]), &tmpCounter);

        itemCounter = buffer[USB_PAYLOAD_LEN_POS] + 2; /* payload length + CRC + end byte TODO: remove magic number*/



        // flag correct startbyte recieved
        ToggleLED2();
        // e.g. sending HEX AB 01 02 03 04 05 06 07 08  via HTerm lets LED toggle
        // AB 02 03 03 CC BB CC 5E BA passes CRC check as well
    }

    // Check if package fully received
    bytesIncoming = GetReadBufferLeft();
    if (bytesIncoming < itemCounter)
    {
        previousReadNotFinished = TRUE;
        return FALSE;
    }
    else
    {
        previousReadNotFinished = FALSE;
    }

    // Read second part of message (till end)
    ReceiveUSBData(&(buffer[USB_PAYLOAD_POS]), &itemCounter);
    itemCounter = USB_PAYLOAD_POS + itemCounter; /* all package length */

    // Verify that second part of data is correct
    if (buffer[itemCounter - 1] != USB_STOP_BYTE)
    {
        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, FALSE);
        return FALSE;
    }

    // Check that CRC is correct (CRC occupies (end-1)th byte)
    if (IsCRC8Correct(&(buffer[1]), (itemCounter - 3), buffer[itemCounter - 2]) == FALSE)
    {
        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, FALSE);
        //TODO: uncomment for debugging
        //return FALSE;
        // ******************************************************************************************************* !!!
    }

    // Unpack data from buffer to struct
    data->msg_id     = buffer[USB_MSG_ID_POS];
    data->asic_id    = buffer[USB_ASIC_ID_POS];
    data->command    = (USBCommandsEnum) buffer[USB_CMD_STAT_POS];
    data->dataLength = buffer[USB_PAYLOAD_LEN_POS];
    for (uint16 i = 0; i < data->dataLength; i++)
    {
        data->data[i] = buffer[USB_PAYLOAD_POS + i];
    }

    // Data receivement and unpacking was successful
    return TRUE;
}
