[pytest]
addopts = --html=..\\TestResults\\AB15_MCU.Tests_result.html --self-contained-html --junitxml=..\\TestResults\\AB15_MCU.Tests_result.xml --json=..\\TestResults\\AB15_MCU.Tests_result.json
testpaths = Tests
markers = 
    basic: marks initial quick-running `smoke tests`
    serial: marks tests related to serial communication PC<->MCU