[pytest]
addopts = -v --capture=tee-sys --color=yes -W ignore::DeprecationWarning --html=..\\TestResults\\AB15_MCU.Tests_result.html --self-contained-html --junitxml=..\\TestResults\\AB15_MCU.Tests_result.xml --json=..\\TestResults\\AB15_MCU.Tests_result.json
testpaths = Tests
python_files = test_*.py
python_functions = test_*
pythonpath = Tests\\fixtures
markers = 
    basic: marks initial, no-additional-setup, quick-running `smoke tests`
    regression: marks tests to be run during regression testing
    advanced: marks tests that require special conditions or additional HW setup to run
    serial: marks tests related to serial communication PC<->MCU
    watchdog: marks Watchdog related Tests
    firing: marks Firing Loop Module rerlated tests