/**********************************************************************************************************************
 * \file gpio.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef GPIO_H_
#define GPIO_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------------Enumerations-----------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Defines pin indexes for CS600 GPIO
 */
typedef enum
{
    CS600_GPIO0 = 0,             /** \brief GPIO pin 0 at CS600 */
    CS600_GPIO1 = 1,             /** \brief GPIO pin 1 at CS600 */
    CS600_GPIO2 = 2,             /** \brief GPIO pin 2 at CS600 */
    CS600_GPIO3 = 3,             /** \brief GPIO pin 3 at CS600 */
    CS600_GPIO4 = 4,             /** \brief GPIO pin 4 at CS600 */
    CS600_GPIO5 = 5,             /** \brief GPIO pin 5 at CS600 */
    CS600_GPIO6 = 6              /** \brief GPIO pin 6 at CS600 */
} GPIOPinsEnum;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Default configuration of GPIO pins (after POR of MCU)
 * Should be executed after POR
 * \return Returns nothing
 */
void InitGPIOPins(void);

/** \brief Configure GPIO pin
 * Can change mode (input/output) and type (push-pull, pull-up, pull-down, etc.)
 * \param pinIdx GPIO pin index as enum value
 * \param mode new mode of pin
 * \return Returns nothing
 */
void ConfigureGPIOPin(GPIOPinsEnum pinIdx, IfxPort_Mode mode);

/** \brief Activate GPIO pin (set pin to high level)
 * Should be configured as output first!
 * \param pinIdx GPIO pin index as enum value
 * \return Returns nothing
 */
void SetGPIOPin(GPIOPinsEnum pinIdx);

/** \brief Deactivate GPIO pin (set pin to low level)
 * Should be configured as output first!
 * \param pinIdx GPIO pin index as enum value
 * \return Returns nothing
 */
void ClearGPIOPin(GPIOPinsEnum pinIdx);

/** \brief Toggle GPIO pin (set pin to opposite level)
 * Should be configured as output first!
 * \param pinIdx GPIO pin index as enum value
 * \return Returns nothing
 */
void ToggleGPIOPin(GPIOPinsEnum pinIdx);

/** \brief Get GPIO pin state
 * Can be used for both input and output pins
 * \param pinIdx GPIO pin index as enum value
 * \return Returns true if pin is in active state (high), false if in deactivated state (low)
 */
boolean GetGPIOPin(GPIOPinsEnum pinIdx);

/** \brief Get all GPIO pins states
 * 0th bit - GPIO0, ..., 6th bit - GPIO6, 7th bit - unused
 *
 * \return Returns all GPIO pins state as variable
 */
uint8 GetGPIOPort(void);

/** \brief Set all GPIO pins states
 * 0th bit - GPIO0, ..., 6th bit - GPIO6, 7th bit - unused
 */
void SetGPIOPort(uint8 portState);

#endif /* GPIO_H_ */
