/**********************************************************************************************************************
 * \file led.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxPort.h"
#include "led.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* LED -> overlaps with SPI function (share pin with SCK)*/
//#define LED                          &MODULE_P10,2                           /* LED Port Pin                         */
#define LED1                         &MODULE_P02,0                           /* LED Port Pin                         */
#define LED2                         &MODULE_P02,1                           /* LED Port Pin                         */
#define LED3                         &MODULE_P02,3                           /* LED Port Pin                         */
#define LED4                         &MODULE_P02,4                           /* LED Port Pin                         */


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void initLEDs(void)
{
    /* Initialize GPIO pins for the LED */
    IfxPort_setPinMode(LED1, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED2, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED3, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED4, IfxPort_Mode_outputPushPullGeneral);

    /* Turn off the LED */
    IfxPort_setPinState(LED1, IfxPort_State_low);
    IfxPort_setPinState(LED2, IfxPort_State_low);
    IfxPort_setPinState(LED3, IfxPort_State_low);
    IfxPort_setPinState(LED4, IfxPort_State_low);

}

void OnLED1(void)
{
    IfxPort_setPinState(LED1, IfxPort_State_high);
}

void OffLED1(void)
{
    IfxPort_setPinState(LED1, IfxPort_State_low);
}

void ToggleLED1(void)
{
    IfxPort_setPinState(LED1, IfxPort_State_toggled);
}


void OnLED2(void)
{
    IfxPort_setPinState(LED2, IfxPort_State_high);
}

void OffLED2(void)
{
    IfxPort_setPinState(LED2, IfxPort_State_low);
}

void ToggleLED2(void)
{
    IfxPort_setPinState(LED2, IfxPort_State_toggled);
}


void OnLED3(void)
{
    IfxPort_setPinState(LED3, IfxPort_State_high);
}

void OffLED3(void)
{
    IfxPort_setPinState(LED3, IfxPort_State_low);
}

void ToggleLED3(void)
{
    IfxPort_setPinState(LED3, IfxPort_State_toggled);
}


void OnLED4(void)
{
    IfxPort_setPinState(LED4, IfxPort_State_high);
}

void OffLED4(void)
{
    IfxPort_setPinState(LED4, IfxPort_State_low);
}

void ToggleLED4(void)
{
    IfxPort_setPinState(LED4, IfxPort_State_toggled);
}

/*blink LED in 0,5Hz rate
 * used for call in 2ms cycle*/
void Blink_LED1_05Hz(void)
{
    static uint16 cntr;

    cntr++;
    if (cntr >=500){
        cntr = 0;
    }

    if (cntr < 250)
    {
        OnLED1();
    }
    else{
        OffLED1();
    }
}



