/**********************************************************************************************************************
 * \file spi.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SPI_H_
#define SPI_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxQspi_SpiMaster.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Structure for QSPI handle required for its functions
 */
typedef struct
{
    IfxQspi_SpiMaster         spiMaster;            /** \brief QSPI Master handle            */
    IfxQspi_SpiMaster_Channel spiMasterChannel;     /** \brief QSPI Master Channel handle    */
} QSPIHandles;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Initialize the QSPI HW and SW handle for operations
 *
 * \return Returns nothing.
 */
void QSPIInitPeriphery(void);

/** \brief Deinitialize the QSPI HW and SW handle for operations
 * Set pins to high-z state (when possible)
 *
 * \return Returns nothing.
 */
void QSPIDeinitPeriphery(void);

/** \brief Initialize SPI transaction and exchange 32bit packages
 * This functions:\n
 * 1) Initiates SPI communication from master side\n
 * 2) Sends 32 bit package to slave\n
 * 3) Receives 32 bit package from slave\n
 * 4) Waits for configured time to avoid issues in communication
 *
 * \param dataToSend pointer to buffer with data to send
 * \param dataToReceive pointer to empty buffer which will be filled with data from slave
 * \param length data length in bytes
 * \return Returns nothing.
 */
void QSPIExchangeData(const uint32 * const dataToSend, uint32 * const dataOut, uint8 length);

#endif /* SPI_H_ */
