/**********************************************************************************************************************
 * \file timer.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxGpt12.h"
#include "IfxPort.h"
#include "periphery/usb.h"
#include "periphery/led.h"
#include "common/Ifx_IntPrioDef.h"
#include "Bsp.h"

#include "timer.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

//extern void ServiceInterruptRoutine(void);
//extern void WatchdogInterruptRoutine(void);
//extern void ErrorCheckInterruptRoutine(void);
//extern void ContinuousReadInterruptRoutine(void);
//extern void GPIOInterruptRoutine(void);
//
///** \brief General timer interrupt routine
// * Implements timers for CS600 watchdog, error check and continuous read
// *
// * \return Returns nothing
// */
//void UpdateTimersRoutine(void);
//
///** \brief Service timer interrupt routine wrapper - calls service interrupt routine function
// * Required for correct interrupt handling
// *
// * \return Returns nothing
// */
//void ServiceTimerRoutineWrapper(void);

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

static uint16 g_watchdogReload;                   /** \brief Watchdog acknowledge periodicity in T2 timer interrupts */
static uint16 g_errorCheckReload;                 /** \brief Error check periodicity in T2 timer interrupts          */
static uint16 g_continuousReadReload;             /** \brief Continuous read periodicity in T2 timer interrupts      */
static uint16 g_GPIOReload;                       /** \brief GPIO handling periodicity in T2 timer interrupts        */

static boolean g_watchdogEnable       = FALSE;    /** \brief Watchdog acknowledge interrupts enable                  */
static boolean g_errorCheckEnable     = FALSE;    /** \brief Error check interrupts enable                           */
static boolean g_continuousReadEnable = FALSE;    /** \brief Continuous read interrupts enable                       */
static boolean g_GPIOEnable           = FALSE;    /** \brief GPIO interrupts enable                                  */

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro defining the Interrupt Service Routines */
IFX_INTERRUPT(UpdateTimersRoutine, 0, ISR_PRIORITY_GPT1_T2_TIMER);

IFX_INTERRUPT(ServiceTimerRoutineWrapper, 0, ISR_PRIORITY_GPT1_T3_TIMER);

void InitGpt12Timer(void)
{
    /* Initialize the GPT12 module */
    IfxGpt12_enableModule(&MODULE_GPT120);                                          /* Enable the GPT12 module      */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_16); /* Set GPT1 block prescaler     */

    /* Initialize the Timer T3 - Service timer*/
    IfxGpt12_T3_setMode(&MODULE_GPT120, IfxGpt12_Mode_timer);                       /* Set T3 to timer mode         */
    IfxGpt12_T3_setTimerDirection(&MODULE_GPT120, IfxGpt12_TimerDirection_down);    /* Set T3 count direction       */
    IfxGpt12_T3_setTimerPrescaler(&MODULE_GPT120, IfxGpt12_TimerInputPrescaler_32); /* Set T3 input prescaler       */
    IfxGpt12_T3_setTimerValue(&MODULE_GPT120, SERVICE_TIMER_PERIODICITY);           /* Set T3 start value           */

    /* Initialize the Timer T2 - General timer */
    IfxGpt12_T2_setMode(&MODULE_GPT120, IfxGpt12_Mode_timer);                       /* Set T2 to timer mode         */
    IfxGpt12_T2_setTimerDirection(&MODULE_GPT120, IfxGpt12_TimerDirection_down);    /* Set T2 count direction       */
    IfxGpt12_T2_setTimerPrescaler(&MODULE_GPT120, IfxGpt12_TimerInputPrescaler_2);  /* Set T2 input prescaler       */
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120, GENERAL_TIMER_PERIODICITY);           /* Set T2 start value           */

    /* Initialize the Service interrupt */
    volatile Ifx_SRC_SRCR *src3 = IfxGpt12_T3_getSrc(&MODULE_GPT120);                /* Get the interrupt address    */
    IfxSrc_init(src3, ISR_PROVIDER_GPT12_TIMER, ISR_PRIORITY_GPT1_T3_TIMER);         /* Initialize service request   */
    IfxSrc_enable(src3);                                                             /* Enable GPT12 interrupt       */

    /* Initialize the General timer interrupt */
    volatile Ifx_SRC_SRCR *src2 = IfxGpt12_T2_getSrc(&MODULE_GPT120);                /* Get the interrupt address    */
    IfxSrc_init(src2, ISR_PROVIDER_GPT12_TIMER, ISR_PRIORITY_GPT1_T2_TIMER);         /* Initialize service request   */
    IfxSrc_enable(src2);
}

void StartServiceTimer(void)
{
    IfxGpt12_T3_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);
}

void StartGeneralTimer(void)
{
    IfxGpt12_T2_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);
}

void StopServiceTimer(void)
{
    IfxGpt12_T3_run(&MODULE_GPT120, IfxGpt12_TimerRun_stop);
}

void StopGeneralTimer(void)
{
    IfxGpt12_T2_run(&MODULE_GPT120, IfxGpt12_TimerRun_stop);
}

void ConfigureWatchdogPeriodicity(uint16 watchdogPeriodicity)
{
    g_watchdogReload = watchdogPeriodicity;
}

void ConfigureErrorCheckPeriodicity(uint16 errorCheckPeriodicity)
{
    g_errorCheckReload = errorCheckPeriodicity;
}

void ConfigureContinuousReadPeriodicity(uint16 continuousReadPeriodicity)
{
    g_continuousReadReload = continuousReadPeriodicity;
}

void ConfigureGPIOPeriodicity(uint16 gpioPeriodicity)
{
    g_GPIOReload = gpioPeriodicity;
}

void EnableWatchdogInterrupt(void)
{
    g_watchdogEnable = TRUE;
}

void EnableErrorCheckInterrupt(void)
{
    g_errorCheckEnable = TRUE;
}

void EnableContinuousReadInterrupt(void)
{
    g_continuousReadEnable = TRUE;
}

void EnableGPIOInterrupt(void)
{
    g_GPIOEnable = TRUE;
}

void DisableWatchdogInterrupt(void)
{
    g_watchdogEnable = FALSE;
}

void DisableErrorCheckInterrupt(void)
{
    g_errorCheckEnable = FALSE;
}

void DisableContinuousReadInterrupt(void)
{
    g_continuousReadEnable = FALSE;
}

void DisableGPIOInterrupt(void)
{
    g_GPIOEnable = FALSE;
}

boolean GetStateWatchdogInterrupt(void)
{
    return g_watchdogEnable;
}

boolean GetStateErrorCheckInterrupt(void)
{
    return g_errorCheckEnable;
}

boolean GetStateContinuousReadInterrupt(void)
{
    return g_continuousReadEnable;
}

boolean GetStateGPIOInterrupt(void)
{
    return g_GPIOEnable;
}

uint16 GetWatchdogPeriodicity(void)
{
    return g_watchdogReload;
}

void UpdateTimersRoutine(void)
{
    // Static variables to simulate separate timers
    static uint16 watchdogCounter           = 0;
    static uint16 errorCheckCounter         = 0;
    static uint16 continuousReadCounter     = 0;
    static uint16 GPIOCounter               = 0;

    // Increment variables if entered interrupt routine
    watchdogCounter++;
    errorCheckCounter++;
    continuousReadCounter++;
    GPIOCounter++;

    // Call corresponding functions if enabled and counter reached reload value
    if ((g_watchdogEnable == TRUE) && (watchdogCounter >= g_watchdogReload))
    {
        // Watchdog acknowledge
        watchdogCounter = 0;
        //WatchdogInterruptRoutine();
    }

    if ((g_errorCheckEnable == TRUE) && (errorCheckCounter >= g_errorCheckReload))
    {
        // Continuous CS600 error check
        errorCheckCounter = 0;
        //ErrorCheckInterruptRoutine();
    }

    if ((g_continuousReadEnable == TRUE) && (continuousReadCounter >= g_continuousReadReload))
    {
        // Continuous registers reading
        continuousReadCounter = 0;
        //ContinuousReadInterruptRoutine();
    }

    if ((g_GPIOEnable == TRUE) && (GPIOCounter >= g_GPIOReload))
    {
        // GPIO handling
        GPIOCounter = 0;
        //GPIOInterruptRoutine();
    }
}

void ServiceTimerRoutineWrapper(void)
{
    // Call interrupt routine function from other file
    //ServiceInterruptRoutine();
}
