/**********************************************************************************************************************
 * \file timer.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef TIMER_H_
#define TIMER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define ISR_PROVIDER_GPT12_TIMER    IfxSrc_Tos_cpu0          /* Interrupt provider                                   */

#define FAST_TIMER_PERIODICITY      50000u  // Test : 4ms             /* Reload value to have an interrupt each  20us*/
                                                              /* fGPT = 100 Mhz
                                                                 (a) IfxGpt12_Gpt1BlockPrescaler_8
                                                                 (b) IfxGpt12_TimerInputPrescaler_1
                                                                 Reload_Value = fGPT / (block Prescaler * input prescaler * irQfreq)
                                                                 Reload_Value = (fGPT  * IRQ_duration) *  / (block Prescaler * input prescaler)
                                                                 Reload_Value = (100000000*0,00002)/(8*1)=250  */

#define SERVICE_TIMER_PERIODICITY   50000u                   /* Reload value to have an interrupt each 200ms         */
#define GENERAL_TIMER_PERIODICITY   625u                     /* Reload value to have an interrupt each 100us  //note: precaler chaned!    */
                                                             /* Reload_Value = (100000000*0,000??5)/(8*2)=625  */



// Calculation formula:
// T = desired IRQ period in seconds
// Reload Value = f_GPT * T / (Gpt1BlockPrescaler ∗ TimerInputPrescaler)
// where f_GPT = 100 MHz --> GPT12 module base frequency,
// T, s - interrupt periodicity
// Gpt1BlockPrescaler - GPT1 block prescaler = 8
// TimerInputPrescaler - timer prescaler = 2
// Reload Value should fit in 16 bit unsigned int!

// T desired = 0,01 --> 10ms
// reload value = (100000000*0,01)/(16*2) = 31250

// T desired = 0,0001 --> 100us
// reload value = (100000000*0,0001)/(16*1) = 625

#define FREQ_GPT12_HZ 100000000                             /* GPT12 module base frequency                           */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Function to initialize the GPT12 Module and configure timers
 * Should be called before starting timers!
 *
 * \return Returns nothing
 */
void InitGpt12Timer(void);

/** \brief Start service timer interrupts
 * Has to be configured first!
 *
 * \return Returns nothing
 */
void StartServiceTimer(void);

/** \brief Start general timer interrupts
 * Has to be configured first!
 *
 * \return Returns nothing
 */
void StartGeneralTimer(void);
void StartFastTimer(void);
/** \brief Stop service timer interrupts
 *
 * \return Returns nothing
 */
void StopServiceTimer(void);

/** \brief Stop general timer interrupts
 *
 * \return Returns nothing
 */
void StopGeneralTimer(void);

/** \brief Configure ASIC watchdog acknowledge periodicity
 * Periodicity is defined in number of General timer interrupts
 *
 * \param watchdogPeriodicity periodicity of reading chunks of data
 * \return Returns nothing
 */
void ConfigureWatchdogPeriodicity(uint16 watchdogPeriodicity);

/** \brief Configure error check periodicity
 * Periodicity is defined in number of General timer interrupts
 *
 * \param errorCheckPeriodicity periodicity of reading error registers in ASIC
 * \return Returns nothing
 */
void ConfigureErrorCheckPeriodicity(uint16 errorCheckPeriodicity);

/** \brief Configure continuous read periodicity
 * Periodicity is defined in number of General timer interrupts
 *
 * \param continuousReadPeriodicity periodicity of reading chunks of data
 * \return Returns nothing
 */
void ConfigureContinuousReadPeriodicity(uint16 continuousReadPeriodicity);

/** \brief Configure GPIO handling periodicity
 * Periodicity is defined in number of General timer interrupts
 *
 * \param gpioPeriodicity periodicity of reading chunks of data
 * \return Returns nothing
 */
void ConfigureGPIOPeriodicity(uint16 gpioPeriodicity);

/** \brief Enable Watchdog interrupt
 * Periodicity has to be configured first!
 *
 * \return Returns nothing
 */
void EnableWatchdogInterrupt(void);
/** \brief Enable Fast interrupt
 * Periodicity has to be configured first!
 *
 * \return Returns nothing
 */
void EnableFastInterrupt(void);

/** \brief Enable error check interrupt
 * Periodicity has to be configured first!
 *
 * \return Returns nothing
 */
void EnableErrorCheckInterrupt(void);

/** \brief Enable continuous read interrupt
 * Periodicity has to be configured first!
 *
 * \return Returns nothing
 */
void EnableContinuousReadInterrupt(void);

/** \brief Enable GPIO handling interrupt
 * Periodicity has to be configured first!
 *
 * \return Returns nothing
 */
void EnableGPIOInterrupt(void);

/** \brief Disable Watchdog interrupt
 *
 * \return Returns nothing
 */
void DisableWatchdogInterrupt(void);

/** \brief Disable Fast interrupt
 *
 * \return Returns nothing
 */
void DisableFastInterrupt(void);

/** \brief Disable error check interrupt
 *
 * \return Returns nothing
 */
void DisableErrorCheckInterrupt(void);

/** \brief Disable continuous read interrupt
 *
 * \return Returns nothing
 */
void DisableContinuousReadInterrupt(void);

/** \brief Disable GPIO handling interrupt
 *
 * \return Returns nothing
 */
void DisableGPIOInterrupt(void);

/** \brief Get error check interrupt state
 *
 * \return Returns true if irq enabled, false - otherwise
 */
boolean GetStateWatchdogInterrupt(void);

/** \brief Get error check interrupt state
 *
 * \return Returns true if irq enabled, false - otherwise
 */
boolean GetStateErrorCheckInterrupt(void);

/** \brief Get error check interrupt state
 *
 * \return Returns true if irq enabled, false - otherwise
 */
boolean GetStateContinuousReadInterrupt(void);

/** \brief Get GPIO interrupt state
 *
 * \return Returns true if irq enabled, false - otherwise
 */
boolean GetStateGPIOInterrupt(void);

/** \brief Gets duration of Watchdog interrupt period
 *
 * \return Returns value of g_watchdogReload variable
 */
uint16 GetWatchdogPeriodicity(void);

#endif /* TIMER_H_ */
