/**********************************************************************************************************************
 * \file usb.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef USB_H_
#define USB_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/** \brief Initializes the USB interface
 * After exiting this function USB communication is possible
 *
 * \return Returns nothing
 */
void InitUSBInterface(void);

/** \brief Send data via USB
 * Writes data to Tx buffer of UART. Sending via USB is done automatically
 *
 * \param buffer pointer to buffer with data to send
 * \param count pointer to number of elements to send
 * \return Returns TRUE if data could be written
 */
boolean SendUSBData(uint8 *buffer, Ifx_SizeT *count);

/** \brief Receive data via USB
 *  Reads data from Rx buffer of UART. Recieving via USB is done automatically
 *
 * \param buffer pointer to buffer where data will be stored
 * \param count pointer to number of elements to read
 * \return Returns TRUE if data could be read
 */
boolean ReceiveUSBData(uint8 *buffer, Ifx_SizeT *count);

/** \brief Gets number of free bytes in UART write buffer (Tx)
 *
 * \return Returns number of free bytes
 */
sint32 GetWriteBufferLeft();

/** \brief Gets number of free bytes in UART read buffer (Rx)
 *
 * \return Returns number of free bytes
 */
sint32 GetReadBufferLeft();

/** \brief Checks if no full messages in UART read buffer (Rx) present
 *
 * \return Returns TRUE if no full message in input buffer
 */
boolean IsInBufferEmpty();

/** \brief Clears UART input (Rx) buffer used for USB communication
 *
 * \return Returns nothing
 */
void CleanUSBInputBuffer();

/** \brief Clears UART output (Tx) buffer used for USB communication
 *
 * \return Returns nothing
 */
void CleanUSBOutputBuffer();

#endif /* USB_H_ */
