using System;
using System.Collections.Generic;

namespace AB15_GUI.WPF.Models;

/// <summary>
/// Constants for receive/transmit package formats
/// Note: should match with package format on MCU
/// </summary>
public static class SerialPackageConstants
{
    // Fields position in package (both send and receive)
    // NOTE: CRC, END byte positions are defined from end of the package
    public const int StartBytePosition      = 0;
    public const int MsgIDPosition          = 1;
    public const int ASICIDPosition         = 2;
    public const int CmdStatusPosition      = 3;
    public const int PayloadLengthPosition  = 4;
    public const int PayloadPosition        = 5;
    public const int CRCPosition            = -2;   /** \brief prelast byte */
    public const int EndBytePosition        = -1;   /** \brief last byte */

    // Fields length in bytes in package (both send and receive)
    // NOTE: for variable length field (payload) max length is provided
    public const int StartByteLength        = 1;
    public const int MsgIDLength            = 1;
    public const int ASICIDLength           = 1;
    public const int CmdStatusLength        = 1;
    public const int PayloadLengthLength    = 1;
    public const int PayloadLength          = 255;  /** \brief maximum length */
    public const int CRCLength              = 1;
    public const int EndByteLength          = 1;

    // Minimum length of full package in bytes
    public const int MinPackageLength       = 6;
}

/// <summary>
/// Constants for certain commands
/// Note: should match with package format on MCU
/// </summary>
public static class CommandsSpecificConstants
{
    public const int readSequenceMaxItems = 32;
    public const int writeSequenceMaxItems = 16;
    public const int rwSequenceMaxItems = 10;
}

/// <summary>
/// Command values for MCU. Occupy cmd field of package
/// Note: should match commands declared in MCU; formatting inherited from MCU code
/// </summary>
public enum MCUCommand
{
    _CMD_MIN                    = 0,                  /** \brief minimal value of command (not included) */

    IS_ALIVE                    = 1,                  /** \brief transaction to check if USB communication works */
    READ_REG                    = 2,                  /** \brief read single register, reports error if unsuccessful */

    _EXT_CMD_MAX                = 63                  /** \brief maximal value of command send via USB, start of internal commands (generated by MCU) */
}

/// <summary>
/// Status values of MCU. Occupy status field of package
/// Note: should match statuses declared in MCU; formatting inherited from MCU code
/// </summary>
public enum MCUStatus
{
    _STATUS_MIN             = 127,             /** \brief minimal value of status (not included) */

    ACK                     = 128,             /** \brief response to is alive transaction */
    ERROR                   = 129,             /** \brief error at MCU or CS600, data holds error info */
    ERROR_TELEMETRY         = 130,             /** \brief error telemetry data of CS600 and MCU */
    STATUS                  = 131,             /** \brief status of MCU, data holds status info/log */
    BUSY                    = 132,             /** \brief MCU is busy processing previous command TODO: check if required */
    DATA                    = 133,             /** \brief response to read or read/write transaction (also works for transactions including such behaviour) */

    _STATUS_MAX             = 255              /** \brief maximal value of command (not included) */
}

/// <summary>
/// Read masks to work with message ID values
/// </summary>
public enum MsgIDMasks
{
    ResponseBit             = 0x80,               /** bit indicating message direction, 0: PC -> MCU, 1: MCU -> PC */
    MCUOnlyBits             = 0x60,               /** bits reserved for messages initiated by MCU (error, status) */
    GeneralPurposeBits      = 0x1F,               /** bits for typical MCU messages in response for PC messages */
}